// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/training-ai/CanalTutor.tsx": () => import("../components/mockups/training-ai/CanalTutor.tsx"),
  "./components/mockups/training-ai/Dashboard.tsx": () => import("../components/mockups/training-ai/Dashboard.tsx"),
  "./components/mockups/training-ai/DetalleCandidato.tsx": () => import("../components/mockups/training-ai/DetalleCandidato.tsx"),
  "./components/mockups/training-ai/Evaluacion.tsx": () => import("../components/mockups/training-ai/Evaluacion.tsx"),
  "./components/mockups/training-ai/ModuloIA.tsx": () => import("../components/mockups/training-ai/ModuloIA.tsx"),
  "./components/mockups/training-ai/PanelTutor.tsx": () => import("../components/mockups/training-ai/PanelTutor.tsx"),
  "./components/mockups/training-ai/PlanCapacitacion.tsx": () => import("../components/mockups/training-ai/PlanCapacitacion.tsx"),
  "./components/mockups/training-ai/ProgresoyLogros.tsx": () => import("../components/mockups/training-ai/ProgresoyLogros.tsx")
};
